# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: MCG-Fun-Markets
description: Prediction Markets Indexer for NFT Floor Prices

contracts:
  - name: MarketFactory
    abi_file_path: ./abi/MarketFactory.json
    handler: ./src/EventHandlers.ts
    events:
      - event: MarketCreated(address indexed marketAddress, address indexed creator, string question, string collectionSlug, uint256 targetPrice, uint256 resolutionTimestamp)
  
  - name: Market
    abi_file_path: ./abi/Market.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Trade(address indexed user, bool indexed outcome, uint256 ethAmount, uint256 shareAmount)
        field_selection:
          transaction_fields:
            - hash
            - value
      - event: MarketResolved(bool winningOutcome, uint256 finalReportedPrice)

networks:
  # Sepolia testnet - main network for testing
  - id: 11155111
    start_block: 0
    hypersync_config:
      url: https://sepolia.hypersync.xyz
    contracts:
      - name: MarketFactory
        address:
          - 0x84ace9de871cdca72aed2df45ef03f92ed643083
      - name: Market
        # Markets are created dynamically, will use wildcard tracking
        
  # Local hardhat network for development
  - id: 31337
    start_block: 0
    rpc_config:
      url: http://127.0.0.1:8545
    contracts:
      - name: MarketFactory
        address:
          - 0x5FbDB2315678afecb367f032d93F642f64180aa3
      - name: Market
        # Markets are created dynamically

# Unordered multichain mode for real-time indexing across chains
unordered_multichain_mode: true

# Preload optimization for faster indexing
# Handlers will run twice, so use Effect API for external calls
preload_handlers: true

# Use lowercase for faster address operations
address_format: lowercase
